ci/test_pre_push.sh

On my Google workstation, I had pylint 1.1.x which has scoring off by default and does not recognize the `--score` flag. Upgrade with `sudo pip install --upgrade pylint`. CircleCI uses the latest (1.7.2).
Setting `--score n` reduces log output, but only reduced the test time from 7:30 (previous run) to 7:10; scoring was not causing the slowness.
Switching from `parallel` to passing the file lists directly to `pylint` significantly sped thigns up, especially on CircleCI. Using `pylint -j 0` for pylint's own parallelism speeds things up slightly (10s -> 8s) locally, but slows things down significantly on CircleCI (11s -> 1m). So I think the moral is parallelism in a constrained / VM environment is not a benefit (even if tools think the machine has 32 cores).

Pylint: Disable scoring and excess parallelism. Log timing and version.

---

rest-api/dao/biobank_order_dao.py
rest-api/test/test-data/biobank_order_1.json
rest-api/test/unit_test/dao_test/biobank_order_dao_test.py

This requires that only the new "createdInfo" keys appear in the request, and not "sourceSite".
Cleanup preparing for automatic pairing in orders/samples.

[DA-280] Remove deprecated BiobankOrder parsing.

---

rest-api/api/biobank_order_api.py
rest-api/api/physical_measurements_api.py
rest-api/dao/biobank_order_dao.py
rest-api/dao/cache_all_dao.py
rest-api/dao/participant_dao.py
rest-api/dao/physical_measurements_dao.py
rest-api/data_gen/fake_participant_generator.py
rest-api/model/participant.py
rest-api/test/test-data/measurements-as-fhir.json
rest-api/test/test-data/physical_measurements_2.json
rest-api/test/test_data.py
rest-api/test/unit_test/api_test/biobank_order_api_test.py
rest-api/test/unit_test/api_test/physical_measurements_api_test.py
rest-api/test/unit_test/dao_test/biobank_order_dao_test.py
rest-api/test/unit_test/dao_test/participant_dao_test.py
rest-api/test/unit_test/dao_test/physical_measurements_dao_test.py
rest-api/test/unit_test/dao_test/site_dao_test.py
rest-api/test/unit_test/offline_test/metrics_export_test.py
rest-api/test/unit_test/unit_test_util.py

* Require that all PhysicalMeasurements (except amendments)  and BiobankOrders have finalizedSiteId.
* Update tests to include site info.
After this is in, we will need to backfill Participant.hpoId and .providerLink, and ParticipantSummary.hpoId. (BiobankOrder and PhysicalMeasurements finalizedSiteId have already been backfilled.)

[DA-384] Auto-pair UNSET participants based on PMs or orders.

---

ci/test.sh
rest-api/dao/participant_dao.py
rest-api/data_gen/fake_participant_generator.py

Shows up in the CircleCI logs:
```
INFO     2017-09-20 20:34:18,575 module.py:832] testing: "POST /rdr/v1/DataGen HTTP/1.1" 200 3
2017-09-20 20:34:18,576 INFO: 200 for POST to http://localhost:8080/rdr/v1/DataGen
2017-09-20 20:34:18,577 INFO: Total participants created: 100
INFO     2017-09-20 20:34:18,580 app_util.py:34] Request protocol: HTTPS=off
INFO     2017-09-20 20:34:18,598 module.py:832] testing: "POST /rdr/v1/DataGen HTTP/1.1" 200 3
2017-09-20 20:34:18,600 INFO: 200 for POST to http://localhost:8080/rdr/v1/DataGen
INFO     2017-09-20 20:34:18,597 deferred.py:311] X-Appengine-Tasketa:1505939658.58, X-Appengine-Country:ZZ, X-Appengine-Current-Namespace:, X-Appengine-Taskretrycount:0, X-Appengine-Queuename:default, X-Appengine-Taskexecutioncount:0, X-Appengine-Taskname:task1 …
```

Fix data gen: Deserialize provider link value. Exercise data gen on CircleCI.

---

rest-api/tools/participant_hpo_backfill.sql

What do you think of this option?
Example output from the SELECT (demonstrating that the `providerLink` JSON is valid and HPO ID is going from 0 to nonzero):
```
+------------+------------+----------------------------------------------------------------------------+
| old_hpo_id | new_hpo_id | provider_link                                                              |
+------------+------------+----------------------------------------------------------------------------+
|          0 |          1 | [{"primary":true,"organization":{"reference":"Organization/PITT"}}]        |
|          0 |          1 | [{"primary":true,"organization":{"reference":"Organization/PITT"}}]        |
|          0 |          1 | [{"primary":true,"organization":{"reference":"Organization/PITT"}}]        |
...
| …
```

[DA-384] SQL to backfill HPO based on BiobankOrder/PhysicalMeasurements.

---

rdr_client/generate_fake_data.py
rest-api/api/data_gen_api.py
rest-api/data_gen/fake_biobank_samples_generator.py
rest-api/executors.py
rest-api/offline/metrics_export.py
rest-api/test/test-data/biobank_order_1.json
rest-api/test/unit_test/api_test/data_gen_api_test.py
rest-api/test/unit_test/unit_test_util.py

* Remove unused single-participant sample generation mode.
* Rewrite sample generation test from single participant to deferred behavior.
* Remove unused make_deferred[_not]_run.
* Add missing column to fake generated CSV.
* Add timestamps to fake BiobankOrder JSON.
* Skip missing timestamps gracefully in data generation.
I should be able to follow the sample generation model fairly directly for PPI generation: Create data for some fraction of participants in deferred execution, test by sending API requests & making the deferred run immediately.

[DA-403] Remove dead data_gen code and fix fake sample generation & test.

---

rdr_client/generate_fake_data.py
rest-api/api/data_gen_api.py
rest-api/data_gen/fake_biobank_samples_generator.py
rest-api/executors.py
rest-api/offline/metrics_export.py
rest-api/test/test-data/biobank_order_1.json
rest-api/test/unit_test/api_test/data_gen_api_test.py
rest-api/test/unit_test/unit_test_util.py

Now data_gen_api passes 1 - fraction_missing into biobank_order_dao.get_ordered_samples_sample() to make sure we don't randomly sample out participants here:
https://github.com/all-of-us/raw-data-repository/blob/master/rest-api/dao/biobank_order_dao.py#L168
This avoids the indeterminism we were seeing earlier.

[DA-403] Roll forward of previous data gen fix

---

rest-api/data_gen/fake_participant_generator.py

Avoids issues when participant is out of date due to biobank order / physical measurement causing pairing under the covers.

Changing fake participant generation to fetch participant before updating it.

---

rdr_client/generate_fake_data.py
rest-api/cron.yaml
rest-api/data_gen/fake_participant_generator.py

Changing metrics pipeline to run at 4 AM, after biobank samples pipeline should have finished.

Fixing data generation to re-fetch participant before updating status; updating metrics pipeline to run at 4 EST.

---

ci/release_notes.py

We used to use it in DA and then move it, but now we only ever use the release ticket in the PD project, so I think we may as well create it there.

Create release tracking ticket in PD project.

---

rest-api/alembic/versions/9a5c2ef1038f_add_participant_view_columns.py

Tested locally after generating fake participants:
```
SELECT race_codes,hispanic FROM participant_view;
+-------------------+----------+
| race_codes        | hispanic |
+-------------------+----------+
| None              |        1 |
| None              |        0 |
| None              |        0 |
| None              |        0 |
| PMI_Other         |        0 |
| PreferNotToAnswer |        0 |
| None              |        0 |
| NHPI              |        0 |
| None              |        0 |
| None              |        0 |
| None              |        0 |
| None              |        0 |
| None              |        0 |
| NHPI              |        0 |
| Black             |        0 |
| MENA              |        0 |
| MENA,AIAN         |        0 |
| None              |        0 |
| …
```

[DA-394] [DA-438] Add more columns to the participant view

---

rest-api/config/base_config.json
rest-api/config/config_prod.json
rest-api/offline/base_pipeline.py

I'm on the fence about the TODO to create JIRA tickets instead, but I figure if someone on GMail recommends tickets over e-mail for alerts, it's worth considering. Certainly getting synchronous errors if alert generation fails would be nice.

[DA-448] Switch sender of alert emails to pmi-drc-alerts, recipient for Biobank data errors to same.

---

rest-api/config/config_stable.json
rest-api/config/config_staging.json
rest-api/config/config_test.json

environments.
(Once we verify this works, we can configure prod as well.)

Whitelisting HPRO app IDs, Vibrent IPs for use in RDR in our non-prod

---

rest-api/config/config_prod.json
rest-api/config/config_stable.json
rest-api/config/config_staging.json

(This is needed to let them publish changes to the codebook.)

[DA-451] Whitelisting vibrent corp IPs for their use of their service account

---

rest-api/dao/database_utils.py
rest-api/offline/main.py
rest-api/offline/public_metrics_export.py
rest-api/test/unit_test/offline_test/metrics_export_test.py
rest-api/test/unit_test/offline_test/public_metrics_export_test.py
rest-api/test/unit_test/unit_test_util.py

For now, we just compute the metrics and return them directly in an approximation of the proposed metrics API.
Open questions:
- Prefixes on code values, e.g. "PMI_" for gender or "PIIState_" for states  - do we care about stripping them and if yes where can we assume a prefix?
- My solution to computing "years old" for both SQLite/MySQL is verbose using the SQL "NOW()" vs passing as parameter may not be ideal, alternative suggestions welcome
- Filter NULL values? Or pass through with a placeholder?
- Do we need to filter down participants first (e.g. check for consent) - or is presence in the particpant_summary table sufficient to include in the metrics?
Still TODO in follow-up PRs:
- Pending a decision on the [design doc](https://docs.google.com/document/d/1KqtsWU-GWd9tYjf8JbcxnmtlVen7O- …

[RW-263] Add public_metrics_export endpoint

---

rest-api/cron.yaml

Actual offline endpoint does not persist metrics yet, just returns them.

[RW-263] Add public metrics cron specification

---

README.md

Somehow this got dropped when rebasing https://github.com/all-of-us/raw-data-repository/pull/545.
Adding it back in.

Adding doc for awardee API

---

rest-api/tools/auth_setup.sh

Local testing showed the following (though highly dependent on *when* I ran the tests):
- no sleep: ~75% failure
- 1s sleep: ~13% failure
- 3s sleep: ~2% failure  <--
- 5s sleep: ~1% failure
- 10s sleep: ~0 failures
10s is too slow for a developer tool and 5s didn't seem much better than 3s. Note: this is hardly scientifically sound as tests were run back-to-back with a sample size of only 30-60 attempts and the cause is entirely environmental.

[DA-485] sleep after IAM key creation

---

rest-api/app_prod.yaml

allow work queue requests for 5000 participants to succeed.

Bumping up prod instances to F2 to get more memory,

---

rest-api/config/config_sandbox.json
rest-api/data_gen/fake_participant_generator.py
rest-api/tools/load_test.sh
rest-api/tools/load_test_locustfile.py

Making FakeParticipantGenerator not depend on app_identity at runtime when run in the context of a load test, as that doesn't work.
Changing load_test.sh to include GAE deps like it used to. (Refactoring FakeParticipantGenerator to not depend on any AppEngine APIs is a bunch of work that I'd like to defer for now; tracked at https://precisionmedicineinitiative.atlassian.net/browse/DA-500)

Adding pmi-hpo-dev (HPRO) to sandbox ACL.

---

rest-api/offline/biobank_samples_pipeline.py
rest-api/test/unit_test/offline_test/biobank_samples_pipeline_mysql_test.py

add a new case where a test is received but not finalized to missing report.

DA-418 change logic for a missing case in reconciliation report

---

rdr_client/import_biobank_samples.py

This script eases development of the Metrics API by running the BiobankSamplesImport endpoint, which marks biobank samples as received and thus ensures full participants are in the local test database.
Example:
```
cd raw-data-repository/rdr_client/
./run_client.sh import_biobank_samples.py
```

[DA-477] Add client for running biobank samples import

---

.editorconfig

Any objections to this?  It will auto-config any compatible editor (such as mine) to use 2-space indents in our Python files, sets "textwrap" to 100, etc.
The failing test is that same unset awardee test, btw.

add a .editorconfig file for 2-space python indents

---

rest-api/README.md
rest-api/test/runner.py

The test output can be a bit spammy with logging messages; this should alleviate that.

Throttle the logging output during unit test runs

---

README.md

In the process of integrating the Organization API into HealthPro, I noticed these stray/missing backticks.

Fix Markdown syntax in documentation

---

rest-api/app_base.yaml
rest-api/offline.yaml

(This ensures that clients will be redirected if they try to use HTTP rather than HTTPS.)

[PD-1519] Adding secure: always to YAML files for all endpoints

---

rest-api/app_base.yaml
rest-api/app_prod.yaml
rest-api/main.py
rest-api/tools/deploy_app.sh

This should make us quicker to handle requests in the event of a big spike in traffic at national launch.

Add warmup handler, bump min_idle_instances to 10 in production.

---

rest-api/dao/participant_counts_over_time_service.py
rest-api/data_gen/fake_participant_generator.py
rest-api/test/unit_test/api_test/participant_counts_over_time_api_test.py

This refines INTERESTED criteria to include individuals who have signed up but not yet consented.  It also adjusts the range of dates used in a calendar for synthetic data generation.  This is needed to ensure Metrics API 1 and Metrics API 2 counts align in our test environment.

[DA-599] Refine INTERESTED criteria and adjust synthetic calendar

---

rest-api/test/unit_test/api_test/data_gen_api_test.py

The data gen endpoint appears to be for testing purposes, and looks to be very non-deterministic. Disable this for now - not sure if it is worth fixing.

[DA-471] Disable flakey data gen test

---

rest-api/tools/setup_database.sh

Also fixing run_cloud_sql_proxy to run (and mysql be invoked with root password) in the grant_permissions.sql case.

Fixing setup_database to set connection string after setting passwords.

---

rest-api/api/base_api.py
rest-api/dao/base_dao.py
rest-api/query.py
rest-api/test/unit_test/api_test/participant_summary_api_test.py

This will optimize WorkQueue pagination in HealthPro.
Ex: When HealthPro sends _offset = 60 & _count = 10 the RDR then returns 10 results starting from 60.
cc: @jt2k

Allow participant summary api to query results using offset field

---

rest-api/etl/run_cloud_etl.sh
rest-api/offline/table_exporter.py
rest-api/tools/auth_setup.sh

This will allow us to run them without interfering with live RDR serving.

[DA-652] Changing Cloud ETL and table exports to occur using replica DB.

---

rest-api/app_base.yaml

AppEngine services when deploying.

Adding skip_files patterns to ignore directories that aren't used by our

---

rdr_client/pairing_assigner.py
rest-api/tools/process_ptsc_pairings.py
rest-api/tools/process_ptsc_pairings.sh

that can be used with pairing_assigner to perform re-pairing.
Adding optional override_site flag to pairing_assigner; the default behavior will be not to alter the pairing of any participant which is already paired with a site (e.g. because they have already completed PM&B).

[PD-2076] Implementing script used to parse pairing data sent by PTSC and turn it into files

---

circle.yml
rest-api/requirements.txt

This package comes in automatically with pyOpenSSL. I couldn't figure out where that package actually comes from (it may already be installed on the OS). That particular package doesn't have a better version, so we need to explicitly upgrade this dep to avoid the vulnerability in 2.2.2.

Upgrade from unsafe cryptography package

---

rdr_client/export_tables.py
rest-api/dao/database_factory.py
rest-api/etl/export_etl_results.sh
rest-api/etl/run_cloud_etl.sh
rest-api/offline/main.py
rest-api/offline/sql_exporter.py
rest-api/offline/table_exporter.py
rest-api/tools/install_config.py

Changing run_cloud_etl to export ETL results after the ETL finishes.
This will 1) isolate prod from the performance impacts of running the ETL, and 2) make sure the data isn't changing while the ETL is in progress.
The current script waits for an hour after the table export and then deletes the instance when it's done... in future we should try polling the task queue or something so that we can delete it as soon as the export finishes.

[DA-652] Change ETL to run against a clone of the RDR main instance.

---

rest-api/etl/export_etl_results.sh
rest-api/etl/run_cloud_etl.sh

Currently must be run from `rest-api`. Fix `--noclone` export flags.

Fix ETL scripts

---

rest-api/dao/physical_measurements_dao.py
rest-api/test/unit_test/api_test/participant_summary_api_test.py
rest-api/test/unit_test/api_test/physical_measurements_api_test.py

add method to check for existing non-cancelled physical measurements  and only set PM.status to cancelled if it is the only measurement.

DA-794 fix pm status bug

---

rdr_client/generate_fake_data.py
rest-api/api/data_gen_api.py
rest-api/data_gen/fake_participant_generator.py
rest-api/main.py

In order to help PTSC backfill a bunch (90k) test participants with biospecimen orders and physical measurements. We want to avoid the random percentages of withdrawn participants and random null measurements or biospecimen orders here.

DA-822 refactor syncthetic data generator to accept a csv of existing participants

---

rest-api/dao/questionnaire_response_dao.py
rest-api/test/test-data/questionnaire_family_history.json
rest-api/test/test-data/questionnaire_family_history_resp.json
rest-api/test/test-data/questionnaire_the_basics.json
rest-api/test/test-data/questionnaire_the_basics_resp.json
rest-api/test/unit_test/api_test/questionnaire_response_api_test.py
rest-api/test/unit_test/dao_test/questionnaire_response_dao_test.py

_Note: This change closes a loophole that was used by many unit tests, it is unknown if Health Pro or PTSC are knowingly or inadvertently using this loophole._ 
Before this change extra/invalid answers added to a questionnaire response were silently ignored.  With this change, every questionnaire response must use either a full set or a sub set of answer link ids found in the questionnaire. No extra or invalid answer link ids are allowed.
Many of the unit tests took advantage of this loophole to use mixed questionnaire and response json data to test for specific answers within the response.  Closing this loophole required refactoring many unit tests and creating new questionnaire and response json data to test with.

[DA-623] Insure questionnaire response answer link ids are valid for questionnaire.

---

rest-api/alembic/versions/335d191204c1_adding_db_functions_for_code_id_lookup_.py

Binary logging is enabled on GCP MySql instances, function that read data require "READS SQL DATA" in the function declaration.

[DA-854] Set deterministic option in new db functions

---

rdr_client/check_ppi_data.py

The check_ppi_data.py script should use ConsentPII_VerifiedPrimaryPhoneNumber value for for matching phone numbers given on the command line.

Fix for [DA-820] Use correct phone number value from spreadsheet

---

rest-api/dao/participant_summary_dao.py
rest-api/test/unit_test/offline_test/biobank_samples_pipeline_test.py

Only set a sample test status to disposed in participant summary when all of the related biobank stored sample records have a bad disposal status.  Sample test status in participant summary should be set to RECEIVED when there are any non-disposed samples or samples with good disposal statuses.

[DA-871] Biobank pipeline hotfix

---

rest-api/test/runner.py

Allows calling the test runner directly with a given test name to run the specified tests
example:
```
test/runner.py $sdk_dir --test-names \
test.unit_test.api_test.participant_counts_over_time_api_test.ParticipantCountsOverTimeApiTest.test_stratification_EHR_CONSENT \
test.unit_test.api_test.participant_counts_over_time_api_test.ParticipantCountsOverTimeApiTest.test_stratification_EHR_RATIO
```

Update test/runner.py to allow test run by names

---

rest-api/test/unit_test/unit_test_util.py

Adds MySQL host lookup using `MYSQL_HOST` environment variable.
Defaults to original behavior if missing.

update unit test utils: allow mysql other than `localhost` via ENV variable

---

.gitignore
rest-api/tools/install_config.py

updates `tools/install_config.sh` to include config mixins from GCS.
- Syncs a hard-coded google cloud storage bucket's contents to a local folder that is ignored by git
- Includes any `.json` files from that folder when building the config
This allows some values to be included in the config on a deployment while not being present in the git repository for security.

[DA-912] Add capability for config mixins from GCS

---

README.md
rest-api/api/base_api.py
rest-api/api/participant_summary_api.py
rest-api/dao/participant_summary_dao.py
rest-api/main.py
rest-api/test/unit_test/api_test/participant_summary_api_test.py

Added an API parameter to disable 60 second backfill buffer.
Added new API 'ParticipantSummary/Modified' to allow grabbing a full table snapshot of what records have changed and what records are new.

[DA-859] Refactor participant summary token sync

---

README.md
rest-api/api/participant_summary_api.py

Move new participant summary modified API documentation.
Require authentication for accessing new participant summary modified API.

[DA-859] Auth and documenation fixes for modified API.

---

rest-api/services/gcp_config.py

This changes the DB services script to point at the Primary DB instead of the Backup DB for the Test and Staging environments.

Only point DB service connections to primary db.

---

rest-api/api/metrics_ehr_api.py
rest-api/dao/metrics_ehr_service.py
rest-api/main.py
rest-api/test/unit_test/api_test/metrics_ehr_api_test.py

This API endpoint performs 3 distinct sub-queries and merges the results into one JSON structure.
Allowing access to the results of each query as separate endpoints will allow the dashboard to load them in parallel instead of one longer request.
This maintains the current `combined` endpoint (for now.)
The `combined` logic is still used in the `PublicMetricsApi`.

DA-982 Metrics EHR endpoint as multiple single-purpose endpoints

---

rdr_common/fhir_utils.py
rest-api/test/unit_test/lib_common_test/fhir_utils_test.py

This does not intend to replace the `fhirclient` python package. We currently use `fhirclient==1.0.6` which supports version 1.0.2 of the FHIR spec. 
This utility is intended to be a stop-gap measure for accessing data in FHIR version R4 data structures without requiring a full upgrade of our current `fhirclient` usage.
_When we eventually upgrade `fhirclient`, this code will become deprecated._

Add a lightweight FHIR R4 object lookup utility

---

rest-api/api/dv_order_api.py

Cancelling a DV order is not covered by consortium requirements, I confirmed PTSC's cancel payload example updates the order status as expected. Also, integrated Tanners new supply delivery code. So this is a kind of pointless PR 🤷‍♂️

DA-992 rebase and confirm cancelled payload updates order status.

---

rest-api/cron_default.yaml
rest-api/cron_prod.yaml
rest-api/cron_sandbox.yaml
rest-api/requirements.txt
rest-api/tools/build_cron_yaml.py
rest-api/tools/deploy_app.sh

This change adds a cron.yaml builder script with inheritance and the ability to override/remove inherited cron jobs.
This is needed so we can have mostly shared cron definitions with a few exceptions.
---
- if project name is `all-of-us-rdr-sandbox`
- use `cron_sandbox.yaml`
- else
- use `cron_default.yaml`
1. Build list of cron files to combine
- start with `cron_default.yaml`
- add `cron_<project_shortname>.yaml` if exists
2. Iterate each job from files in order
- identify jobs by `description` (cannot be overridden or removed if missing `description`)
- add new jobs
- overwrite existing jobs
- remove existing job if new job is missing either `url` or `schedule` (the required fields)
3. Serialize compiled job list as `cron.yaml`

update deploy process with Cron YAML builder

---

rest-api/genomic/genomic_set_file_handler.py
rest-api/model/base.py
rest-api/model/biobank_dv_order.py
rest-api/model/genomics.py
rest-api/test/unit_test/offline_test/genomic_pipeline_test.py

'created' and 'modified' fields for 'biobank_dv_order', 'genomic_set' and 'genomic_set_member' are now auto populated using sqlalchemy listener hooks.  There should be no need to manually set those column values.

Fix auto population for 'created' and 'modified' columns in new tables.

---

rest-api/dao/questionnaire_response_dao.py
rest-api/test/unit_test/api_test/questionnaire_response_api_test.py
rest-api/test/unit_test/unit_test_util.py

This fixes the datetime exception error when comparing authored dates, where one date has tzinfo and the other does not.

[DA-1117] Fix exception error on duplicate questionnaire submissions

---

rest-api/dao/dv_order_dao.py
rest-api/test/test-data/dv_order_api_post_supply_delivery_alt.json

🚨HOTFIX🚨:  Made expected delivery date optional for supply-delivery calls and removed the field from one of the test order json files to prove.

DA-1159 make expected delivery date optional

---

rest-api/services/gcp_config.py

The production backup replica DB instance went bad, running disk space up to 3.3 TB vs 118 GB for the primary instance.  Created new replica named `rdrbackupdb-a` and deleted old backup replica.
During this, I created a new Staging backup replica instance named `rdrbackupdb` to match original naming convention and deleted `rdrbackupdb1` instance.

[ROC-16] updated production and staging DB replica name

---

rest-api/dao/metrics_ehr_service.py
rest-api/test/unit_test/api_test/metrics_ehr_api_test.py

This makes the two apis for consented/received use the same filtering rules.
also adds some tests to confirm it.

[DA-1119] ehr metrics fix filter logic to be consistent

---

rest-api/config.py
rest-api/config/base_config.json
rest-api/config/config_dev.json
rest-api/config/config_prod.json
rest-api/config/config_sandbox.json
rest-api/config/config_stable.json
rest-api/config/config_staging.json
rest-api/config/config_test.json
rest-api/offline/update_ehr_status.py
rest-api/test/unit_test/offline_test/update_ehr_status_test.py

The existing bigquery table names were hard-coded. A view needed to change immediately after the initial release so this work allows changing the data view sources via the configuration.

[DA-1220] make ehr update data sources configurable

---

rest-api/cloud_utils/bigquery.py
rest-api/dao/metrics_ehr_service.py
rest-api/offline/update_ehr_status.py
rest-api/test/unit_test/api_test/metrics_ehr_api_test.py
rest-api/test/unit_test/cloud_utils_test/bigquery_test.py
rest-api/test/unit_test/offline_test/update_ehr_status_test.py

This changeset does two things:
1. improve robustness when parsing data from biquery (handle new edge cases)
2. adjust filter logic for two queries to make the counts identical

v1-50-v5 HOTFIX: EHR Metrics API and Update cron job fixes

---

rest-api/dao/dv_order_dao.py

Fixes Mayolink validation errors
1. Patient gender is not included in the list
2. Physician name can't be blank

[DA-1226] Fixes for sending to Mayolink API

---

rest-api/tools/tool_libs/_oauth_key.py

Just a simple tool to quickly get the oauth token for your PMI account or a service account for any project.  It creates the key if needed (for service accounts) and prints the oauth token.  Then it waits until you press `ctrl-c` and then it exits and cleans up any service account keys.
**Invocation examples**
1. `python -m tools oauth-token --project all-of-us-rdr-sandbox`
2. `python -m tools oauth-token --project all-of-us-rdr-stable --service-account configurator@all-of-us-rdr-stable.iam.gserviceaccount.com`

Tool to get account/service account oauth token

---

rest-api/api/base_api.py
rest-api/api/bigquery_participant_summary_api.py
rest-api/cloud_utils/bigquery.py
rest-api/dao/base_dao.py
rest-api/dao/bigquery_sync_dao.py
rest-api/main.py
rest-api/model/bq_base.py

Codacy will fail on building a query string.  Since this does take user input, I have added validation to verify the user input is actually a numeric 9-digit value before running the BigQuery query.
I have added a testing, non-production, API for testing BigQuery queries.  
Example: https://all-of-us-rdr-sandbox.appspot.com/rdr/v1/Participant/P255612093/TestSummary

[DA-1222] Update POST/PUT methods to regenerate Json for BQ

---

rest-api/dao/participant_dao.py
rest-api/dao/questionnaire_response_dao.py

Two change:
1. In _update_participant_summary method, it will get the participant and participant_summary for updating, this will lock the table, so we need to commit the change immediately to db to reduce the lock time. In the previous logic, it shares the session with other operations, the change can only be commit after all other operations are done, that make the lock longer.
2. remove the nested get_for_update for participant.

[DA-1192] use an independent session for participant summary update

---

rest-api/dao/bigquery_sync_dao.py
rest-api/model/bq_base.py
rest-api/model/bq_participant_summary.py
rest-api/test/unit_test/cloud_utils_test/bigquery_schema_test.py
rest-api/test/unit_test/dao_test/bigquery_sync_dao_test.py

This PR adds a calculation for distinct number of visits modeled after Michael's backfill sql logic.
This also fixes the problem that was causing records to fail on insert into BQ.
Lastly, changed the Physical Measurements to be a sub-table as there can be multiple PM records.

[DA-1233] BQ - calculate distinct visits and fix sync errors

---

rest-api/dao/bigquery_sync_dao.py
rest-api/model/__init__.py
rest-api/model/bq_participant_summary.py
rest-api/test/unit_test/dao_test/bigquery_sync_dao_test.py
rest-api/tools/tool_libs/bq_migrate.py

I decided to add prefixes to all the sub-tables in the BQ particpant summary because there were too many duplicate fields names across the sub-tables which made creating a view extra difficult.  Adding prefixes alleviates the need to add aliases to the sub-table fields in table views.
**Because of this sub-table field naming change.  When this PR is merged, the following steps need to be manually done after the deploy for each environment this PR goes into.  There will be BQ sync cron job errors until these steps are completed.**
1. Run the migrate-bq tool to delete existing tables and views. 
**`python -m tools migrate-bq --project all-of-us-rdr-XXXXX --dataset rdr_ops_data_view --delete all`**
2. Run the migrate-bq tool again to create the tables and views. 
**`python -m tools …

[DA-1221] Create BQ view for analytics team

---

rdr_service/.configs/db_config.json
rdr_service/dao/database_factory.py
tests/dao_tests/test_site_dao.py
tests/helpers/mysql_helper.py
tests/helpers/unittest_base.py
tests/test_environment.py

Dropped using a connection string from the os environment, now uses a dedicated unittest connection string in the local connection config file (.configs/db_config.json).
ALSO remember to call super() for BaseTestCase.setUp().

Fixed up database connection to use a dedicated unittest connection

---

rest-api/cron_prod.yaml
rest-api/offline/bigquery_sync.py

Reduce batch rebuild size to 100.
Enable production cron bigquery sync job.

Hotfix for minor bigquery fixes

---

rest-api/cron_default.yaml
rest-api/dao/bigquery_sync_dao.py
rest-api/offline/bigquery_sync.py

Set bigquery sync cron job to run every 2 minutes.
Ensure we are joining with `bigquery_sync` correctly to get the list of participant ids to rebuild.
Removed an unneeded logged warning.
Changed task batch size from 100 to 300.

Minor fixes to bigquery sync

---

rest-api/cron_prod.yaml
rest-api/cron_staging.yaml
rest-api/cron_test.yaml

Genomic pipeline are testing only on stable env. Other env don't have those buckets, will throw error. Disable genomic pipeline on other envs in this PR and will enable prod when it go live.

only_enable_genomic_pipeline_on_stable

---

app.yaml
main.py
rdr_service/app_base.yaml
rdr_service/celery_test.py
rdr_service/data_gen/fake_participant_generator.py
rdr_service/main.py
rdr_service/services/celery_utils.py
rdr_service/services/gunicorn_config.py
rdr_service/services/supervisor.conf
rdr_service/version_api.py
requirements.in
requirements.txt

Force amqp package version to 2.1.1 for now.

Enable supervisor/celery/gunicorn to run on AppEngine 2

---

rdr_service/api/base_api.py
rdr_service/api/data_gen_api.py
rdr_service/api/import_codebook_api.py
rdr_service/api/questionnaire_response_api.py
rdr_service/cloud_utils/bigquery.py
rdr_service/dao/bq_participant_summary_dao.py
rdr_service/offline.yaml
rdr_service/offline/base_pipeline.py
rdr_service/offline/bigquery_sync.py
rdr_service/offline/sa_key_remove.py
rdr_service/offline/sync_consent_files.py
rdr_service/services/celery_utils.py
rdr_service/services/gunicorn_config.py
rdr_service/services/supervisor.conf
rdr_service/storage.py
rdr_service/version_api.py

This only covers the 7 cron jobs that show up on Sandbox.  The other cron jobs need testing.
This added two celery queue types, a `default` queue and an `offline` queue so running the BigQuery rebuild would not block all background tasks until it completes.

Get offline cron jobs working.

---

rest-api/cron_default.yaml

We tried to move ParticipantCountsOverTime cron job to 23:00, but it's failed with deadlock error.
Move it back to 3:30.

modify_participant_count_cronjob_time

---

.circleci/config.yml
ci/test.sh
main.py
rdr_service/.configs/db_config.json
rdr_service/dao/bigquery_sync_dao.py
rdr_service/dao/bq_hpo_dao.py
rdr_service/dao/bq_organization_dao.py
rdr_service/dao/bq_site_dao.py
rdr_service/dao/database_factory.py
rdr_service/offline/bigquery_sync.py
rdr_service/services/flask.py
rdr_service/tools/import_organizations.py
rdr_service/tools/setup_local_database.sh
tests/helpers/mysql_helper.py

Fixes a minor BigQuery sync issue.
Fixes the `localhost` BigQuery sync issue after running `import_organizations.sh`.
Use the DB connection string created by the cli tools when they are run.  Otherwise we only connect to our localhost DB when running cli tools.

Py3 BigQuery Fixes for Sync process and Import Organizations

---

rdr_service/dao/bq_participant_summary_dao.py

After viewing errors in the logs, looks like we need a retry loop here to keep trying for a while until the initial participant table record is available.

BigQuery background task: retry looking up participant record.

---

rdr_service/dao/dv_order_dao.py

Per DA-1315: # 1.) 
> possible typo: supplyDelivery error message when participant without primary consent "No summary for particpant id: 927711636".

Fixed error message typo.

---

rest-api/dao/metrics_cache_dao.py
rest-api/dao/participant_counts_over_time_service.py
rest-api/offline/participant_counts_over_time.py
rest-api/test/unit_test/api_test/participant_counts_over_time_api_test.py
rest-api/test/unit_test/api_test/public_metrics_api_test.py

The idea is to create a temp table at the very beginning to store all the participant and participant summary data.
And then run the cron job against the temp table, so it will not lock the participant and participant summary tables.

tune_metrics_v2_cron_job

---

rdr_service/dao/dv_order_dao.py
rdr_service/model/biobank_dv_order.py
requirements.txt
tests/api_tests/test_dv_order_api.py
tests/dao_tests/test_dv_order_dao.py

Added `biobankStatus` to API test. Removed from DAO test. Writing 'status' field from Mayolink's response to `biobankStatus`.

Modified biobankStatus to source from Mayolink's API

---

rest-api/api/dv_order_api.py
rest-api/api_util.py
rest-api/dao/dv_order_dao.py
rest-api/model/biobank_dv_order.py
rest-api/services/gcp_db_daemon.py
rest-api/test/unit_test/api_test/dv_order_api_test.py
rest-api/test/unit_test/dao_test/dv_order_dao_test.py

This PR changed the source for `biobank_order_identifier.system` to be the authenticated user supplying the `SupplyDelivery` and `SupplyRequest` payloads.
The constants related to the DV order system were refactored to reflect multiple providers, currently Vibrent and Care Evolution. Because the `SupplyRequest` and `SupplyDelivery` payloads are agnostic of which provider is supplying the payload, the authenticated user making the API call was used to determine the source for `biobank_order_identifier.system`.
Additional Notes:
- The system identifier for Care Evolution was assumed to be `http://carevolution.be` based on induction: the system identifier for Vibrent is `http://vibrenthealth.com`.
- A cloud DB proxy was created for the Care Evolution test environment.

[DA-1338] Set biobank_order_identifier.system based on user

---

rdr_service/api/dv_order_api.py
rdr_service/api_util.py
rdr_service/app_util.py
rdr_service/config.py
rdr_service/dao/dv_order_dao.py
rdr_service/model/biobank_dv_order.py
rdr_service/model/bq_base.py
rdr_service/services/gcp_db_daemon.py
tests/api_tests/test_dv_order_api.py
tests/dao_tests/test_dv_order_dao.py

Additionally:
- Constants now named to allow for multiple Salivary DV providers (Vibrent AND Care Evolution).
- Care Evolution added to Google cloud proxy. 
- Expanded tests to allow for switching of authenticated user's email locally.
- setup_local_database.sh errors fixed (bq_base)

[DA-1338] Setting biobank_order_identifier.system based on user

---

rdr_service/api/awardee_api.py
rdr_service/api/base_api.py
rdr_service/api/check_ppi_data_api.py
rdr_service/api/data_gen_api.py
rdr_service/api/dv_order_api.py
rdr_service/api/metrics_api.py
rdr_service/api/participant_counts_over_time_api.py
rdr_service/api/public_metrics_api.py
rdr_service/api/questionnaire_api.py
rdr_service/config_api.py
rdr_service/dao/base_dao.py
rdr_service/dao/biobank_order_dao.py
rdr_service/dao/code_dao.py
rdr_service/dao/dv_order_dao.py
rdr_service/dao/metrics_dao.py
rdr_service/dao/organization_hierarchy_sync_dao.py
rdr_service/dao/participant_dao.py
rdr_service/dao/participant_summary_dao.py
rdr_service/dao/physical_measurements_dao.py
rdr_service/dao/questionnaire_response_dao.py
rdr_service/main.py

This PR updates string formatting of logged messages in the `rdr_service` directory from the Python 2 method to the Python 3 method. Google logging with Python 3 does not support the Python 2 string formatting method.

[DA-1359] Updated logging, exceptions formatting for Python 3.

---

.idea/runConfigurations/Tool__Migrate_BQ.xml
rdr_service/services/gcp_config.py
rdr_service/services/gcp_utils.py
rdr_service/services/system_utils.py
rdr_service/tools/tool_libs/_program_template.py
rdr_service/tools/tool_libs/app_engine_manager.py
rdr_service/tools/tool_libs/tools.bash

Includes the following tools;
deploy : Deploy a branch/tag to GCP app engine.
list : List app engine services and versions.
split-traffic: Change traffic allocations between versions on app engine.
Updated bash completion script.
Minor code clean up with moving some output to debug messages.

[DA-1364] Create new style tools to manage python3 deployments.

---

rdr_service/api/base_api.py
rdr_service/api/import_codebook_api.py
rdr_service/api/questionnaire_response_api.py
rdr_service/dao/bq_participant_summary_dao.py
rdr_service/queue.yaml

Improve SQL performance by replacing use of `sp_get_questionnaire_answers` stored proc with more efficient queries.

[DA-1373] Put one-off BQ tasks in own queue

---

tests/cron_job_tests/test_genomic_pipeline.py

Sorting the `files_processed` list in place to enforce ordering for testing genomic filenames.

[bug-fix] Explicitly ordering test-file list.
