rest-api/tools/README.md, rest-api/tools/export_tables.py, rest-api/tools/export_tables.sh
To be used after running RDR -> OMOP ETL, and for other purposes (e.g. generating CSV data for PPI review.)
=> Adding export tables utility

rdr_client/generate_fake_data.py, rest-api/api/data_gen_api.py, rest-api/data_gen/fake_biobank_samples_generator.py, rest-api/executors.py, rest-api/offline/metrics_export.py, rest-api/test/test-data/biobank_order_1.json, rest-api/test/unit_test/api_test/data_gen_api_test.py, rest-api/test/unit_test/unit_test_util.py
This reverts commit e11f90127a1e7a28d3b31fde004493ba6a88d2a3.
CircleCI is failing on master and flakily on working branches, but tests are passing locally, after this commit.
=> Revert "[DA-403] Remove dead data_gen code and fix fake sample generation & test. (#488)"

rest-api/alembic/versions/89dd3b8f4447_fix_participant_view.py
(I tested this in the test env.)
=> Fixing  questionnaire_response_answer_view to do an inner join (not cross join) on participant_summary.

rest-api/alembic/versions/7e250583b9cb_add_qra_qr_id.py, rest-api/tools/generate_questionnaire_response_answer_spec.py, rest-api/tools/generate_questionnaire_response_answer_spec.sh
Updating questionnaire_response_answer_view to contain questionnaire response ID. (Used for calculating number of questionnaire responses in spec.)
=> [DA-403] Adding script for generating PPI answer spec.

rest-api/app_data/answer_specs.csv, rest-api/data_gen/fake_participant_generator.py, rest-api/tools/import_questionnaires.sh
Changing import_questionnaires.sh to pull latest questionnaires from github.
=> [DA-403] Synthetic PPI generation based on CSV spec

rest-api/README.md, rest-api/tools/setup_env.sh
Note: these instructions don't entirely work currently (but I don't think they are any more broken than before), but will with the follow-up refactoring PR.
=> Improve README and update commandlines

rdr_client/export_tables.py
Bill Schultz required info from this doc for release approval; adding a link to it from the codebase so it can be found in the future.
=> Add link to permissions management doc for ExportTables.

rest-api/config/config_stable.json, rest-api/config/config_staging.json
(We get an error trying to whitelist IP4 without this.)
=> Adding empty ip6 blocks

rest-api/etl/etl.sql, rest-api/etl/run_cloud_etl.sh, rest-api/etl/run_local_etl.sh
Making ETL scripts extra verbose.
=> ETL optimizations to improve performance.

rest-api/dao/participant_summary_dao.py, rest-api/test/unit_test/dao_test/participant_summary_dao_test.py
I'm not sure if this column is used anywhere, seems important.. If yes - likely need to backfill if we care about the test env.
=> Fix enrollment status update bug

rest-api/dao/organization_dao.py, rest-api/data/awardees.csv, rest-api/data/organizations.csv, rest-api/data/sites.csv, rest-api/model/site.py, rest-api/singletons.py, rest-api/tools/csv_importer.py, rest-api/tools/export_organizations.sh, rest-api/tools/import_organizations.py, rest-api/tools/import_organizations.sh
Refactoring common logic to CsvImporter class.
New script that exports data from Google Sheets in CSV format and puts in the data dir.
Checking in new fake data files as well; won't be used in prod until we have real data that takes the place of our current data in test/test-data/hpos.csv and sites.csv.
=> [DA-463] New awardee/organization/site importer script.

rest-api/tools/view_export_files.sh
Using exporter service account credentials.
=> Adding tool for viewing deidentified export files

rest-api/api_util.py, rest-api/dao/participant_dao.py, rest-api/data/awardees.csv, rest-api/test/client_test/participant_test.py, rest-api/test/unit_test/api_test/participant_api_test.py
* changed logic in pairing _do_update to make provider link the priority
* fixed participant test to reflect changes in awardee.csv with UNSET row
=> Provider link pairing fix

rest-api/dao/biobank_order_dao.py, rest-api/dao/physical_measurements_dao.py, rest-api/test/client_test/participant_test.py, rest-api/test/test-data/biobank_order_1.json, rest-api/test/test-data/biobank_order_2.json, rest-api/test/unit_test/api_test/biobank_order_api_test.py, rest-api/test/unit_test/api_test/participant_summary_api_test.py, rest-api/test/unit_test/dao_test/biobank_order_dao_test.py, rest-api/test/unit_test/dao_test/physical_measurements_dao_test.py, rest-api/test/unit_test/offline_test/biobank_samples_pipeline_mysql_test.py
Pair at biospecimen collected site.
=> Change pmb site pairing

rest-api/config/config_prod.json, rest-api/config/config_stable.json, rest-api/config/config_staging.json
=> add whitelist IP's

rest-api/dao/biobank_stored_sample_dao.py, rest-api/test/unit_test/offline_test/biobank_samples_pipeline_test.py
=> DA-515 ignore un-recognized tests

rest-api/test/unit_test/dao_test/questionnaire_response_dao_test.py
Last Modified introduced a feature not in the tests for Skip Codes; I failed to merge master into my branch before merging.  This rectifies that.
=> Fix a test for skip codes

README.md
referenced awardee and hpoId mapping.
=> DA-568 add note for participantSummary in README

rest-api/tools/deploy_app.sh
app.yaml and cron.yaml are generated.
=> Changing deploy_app so git status check occurs before

rest-api/config/base_config.json, rest-api/dao/participant_counts_over_time_service.py
Don't think this needs to be added any where else.
=> DA-594 add 1ed10 to dna sample test code

rest-api/tools/auth_setup.sh
between backup and main replica.
=> Grep for quote before db_connection_name to distinguish

rest-api/offline/metrics_pipeline.py
see if it fixes metrics discrepancies.
(I will give this a try in sandbox.)
=> [DA-612] Switching to use GoogleCloudStorageConsistentOutputWriter to

rest-api/etl/etl.sql, rest-api/etl/setup_database_for_etl.sh
Tweaking column lengths in ETL SQL, truncating measurement value strings at 1024.
=> Changing setup_database_for_etl to read root password from db_config.

rest-api/tools/import_organizations.py, rest-api/tools/import_organizations.sh
=> Setting a dummy latitude and longitude to all sites when importing

rest-api/test/test-data/healthpro_stable_participants.csv, rest-api/tools/import_participants.py
Python does not pass integers by reference
=> [DA-634] Update test participants, fix import_participants script

rest-api/etl/set_empty_strings_to_null.sql, rest-api/etl/setup_local_database_for_etl.sh
concept_relationship to NULL when it was '' after import.
=> [DA-638] Changing ETL setup to set invalid_reason on concept,

rest-api/etl/setup_local_database_for_etl.sh, rest-api/etl/source_to_concept_map.csv
=> Adding source_to_concept_map.csv

rest-api/etl/source_to_concept_map.csv
@danqrodney  I wasn't sure about the local phi vocabularies used, but i created one called ppi-sex for "SexAtBirth" mappings.
=> Added mapping for ethnicity and sex at birth mappings

rest-api/etl/etl.sql, rest-api/etl/setup_local_database_for_etl.sh
Stripping concept_relationships down to just "Maps to" since that's all we need for the ETL.
Using same sort of logic for populating gender and ethnicity as we use for race in the ETL.
=> [DA-645] Making ETL use same vocabulary that curation uses.

rest-api/dao/organization_dao.py, rest-api/dao/participant_dao.py, rest-api/dao/participant_summary_dao.py, rest-api/dao/site_dao.py, rest-api/etl/etl.sql, rest-api/etl/set_empty_strings_to_null.sql, rest-api/test/unit_test/dao_test/participant_dao_test.py, rest-api/tools/import_organizations.py, rest-api/tools/setup_database.sh
Changing participant summary API to handle withdrawalTime not being set for withdrawn participants.
=> [DA-680] Copying over withdrawalTime, suspensionTime on participant update.

rest-api/tools/ehr_upload.py, rest-api/tools/ehr_upload.sh
Pending one question on what we will do with participants who are not paired at site level, but other than that, this is done.
=> DA-688 ehr upload consent docs

rest-api/config.py, rest-api/config/config_staging.json, rest-api/config/config_test.json, rest-api/offline/sa_key_remove.py
Add key deletion exception for redlock-read-only-stable and circle-deploy in staging config.
Add key deletion exception for circle-deploy in test config.
=> [DA-728] Add exception list for service account from key deletion

rest-api/app_util.py, rest-api/config/config_prod.json, rest-api/config/config_stable.json
update stable and prod config to whitelist ip ranges for awardee-tach.
=> PD-2329 update stable and prod configs for awardee trans_am (tach).

opsdataAPI.md
Add endpoints below to the ops data api readme:
stable: all-of-us-rdr-stable.appspot.com/rdr/v1
prod: all-of-us-rdr-prod.appspot.com/rdr/v1
=> [DA-743] add endpoints to ops readme

rest-api/alembic/versions/380d2c363481_add_login_phone_number_column.py
re-generate alembic file for login_phone_number
=> [DA-723] fix alembic version conflict

opsdataAPI.md
=> minor improvements for readability of ops data api.

rest-api/etl/run_cloud_etl.sh
=> Changing ETL to run against live DB, not replica, since writes against

rest-api/alembic/versions/c7c4b2f17f46_add_enrollment_status_time_to_.py
resolve alembic version conflict
=> [DA-769] resolve alembic version conflict

rest-api/etl/etl.sql
All DB values are currently null for this column.
=> [DC-242] Fix PM status check to also accept null

rest-api/dao/biobank_order_dao.py, rest-api/test/unit_test/api_test/biobank_order_api_test.py, rest-api/test/unit_test/dao_test/biobank_order_dao_test.py
Add biobank order to history on initial insert
Add test for new orders inserted to history
=> DA-783 add biobank oder to history on insert.

README.md, opsdataAPI.md
update readme for primaryLanguage
=> [DA-786] update_readme_for_primaryLanguage

rest-api/dao/participant_counts_over_time_service.py, rest-api/dao/participant_summary_dao.py, rest-api/test/test-data/dv_ehr_share_consent_questionnaire.json, rest-api/test/test-data/ehr_consent_questionnaire.json, rest-api/test/unit_test/api_test/participant_summary_api_test.py
count dvehr sharing yes as member or core
=> [DA-785] Wangy70/count dvehr sharing yes as member or core

rest-api/dao/biobank_order_dao.py, rest-api/offline/biobank_samples_pipeline.py, rest-api/test/unit_test/dao_test/biobank_order_dao_test.py, rest-api/test/unit_test/offline_test/biobank_samples_pipeline_mysql_test.py
Remove 24hour report, change received and missing to cover 10 hours. Add a new modified report.
=> [DA-778] Wangy70/implement biobank reconciliation reports

rest-api/dao/physical_measurements_dao.py, rest-api/test/unit_test/api_test/physical_measurements_api_test.py, rest-api/test/unit_test/dao_test/physical_measurements_dao_test.py
Remove created site and finalized site from cancelled orders. Add condition to check for new measurements being inserted. Add tests.
=> physical measurements bug fix for new orders.

rest-api/test/test-data/healthpro_stable_participants.csv
add test participants to stable
=> [DA-810] add test participants to stable

README.md, opsdataAPI.md
update readme for loginPhoneNumber
=> [DA-723] update readme for loginPhoneNumber

rest-api/data/sites.csv
=> [DA-815] import sites

rest-api/cron_default.yaml, rest-api/offline/biobank_samples_pipeline.py, rest-api/offline/main.py, rest-api/test/unit_test/offline_test/biobank_samples_pipeline_mysql_test.py
implement 60 days biobank reconciliation reports
=> [DA-803] implement 60 days biobank reconciliation reports

rest-api/app_base.yaml, rest-api/services/README.md, rest-api/services/_daemon_template.py, rest-api/services/daemon.py, rest-api/services/gcp_config.py, rest-api/services/gcp_db_daemon.py, rest-api/services/gcp_utils.py, rest-api/services/system_utils.py
This allows database connections for graphical interface tools such as MySQL Workbench and PyCharm.
=> Allow running google_sql_proxy as a service to allow persistent db connections

rest-api/offline/biobank_samples_pipeline.py, rest-api/offline/sql_exporter.py
reconciliation pipeline OOM issue
=> [824] reconciliation pipeline OOM issue

rest-api/offline/biobank_samples_pipeline.py
fix reconciliation pipeline bug
=> [DA-826] fix reconciliation pipeline bug

rest-api/data/sites.csv
=> [DA-834] import sites

rest-api/offline/biobank_samples_pipeline.py
Biobank samples import pipeline could handle bad biobank IDs more gracefully
=> DA-601 - Ensure biobank id exists before importing sample

rdr_client/check_ppi_data.py, rest-api/api/check_ppi_data_api.py, rest-api/dao/participant_summary_dao.py, rest-api/test/unit_test/api_test/check_ppi_data_api_test.py
Removed unused get email method in ParticipantSummaryDao.
=> [DA-820] Allow running check_ppi_data.py with phone numbers to identify participants

rest-api/api/participant_counts_over_time_api.py, rest-api/dao/participant_counts_over_time_service.py, rest-api/test/unit_test/api_test/participant_counts_over_time_api_test.py
=> [DA-671] Wangy70/refactor m2 api

rest-api/dao/participant_counts_over_time_service.py
convert timestamp to date type before compare
=> [DA-671] fix m2api sql

rest-api/test/test-data/healthpro_stable_participants.csv
import test participant to stable
=> [DA-846] import test participant to stable

rest-api/tools/setup_database.sh
Changed output forward option from overwrite to append
=> [DA-853] setup database script does not correctly set permissions on RDR db.

rest-api/offline/biobank_samples_pipeline.py, rest-api/test/test-data/biobank_samples_1.csv, rest-api/test/unit_test/offline_test/biobank_samples_pipeline_test.py
Code from DA-601 did not check that 'sample' var was not None.  This fixes that and adds child sample data for unittests to simulate the same situation.
=> [v1-39-rc1] Bio bank pipeline hot fix

rest-api/dao/metrics_cache_dao.py, rest-api/dao/participant_counts_over_time_service.py, rest-api/participant_enums.py, rest-api/test/unit_test/api_test/participant_counts_over_time_api_test.py
migrate m1api to m2api for age range stratification
=> [DA-864] migrate m1api to m2api for age range stratification

rest-api/dao/participant_counts_over_time_service.py
run cron job insert sql against main db instead of failed over db
=> [DA-864] run cron job insert sql against main db instead of failed over db

rest-api/dao/participant_summary_dao.py, rest-api/offline/biobank_samples_pipeline.py, rest-api/test/test-data/biobank_samples_1.csv, rest-api/test/unit_test/offline_test/biobank_samples_pipeline_test.py
This updates master with the v1-38-rc2 hotfix commits.
=> [DA-871] merge v1-39-rc2 hotfix into master

rest-api/tools/import_organizations.py
This was a bug caused by bad indentation:
```
for site in sites_to_remove:
old_site = ...
if old_site: ...
```
=> [DA-866] Fix site deletion / obsolete logic

rest-api/services/daemon.py, rest-api/services/gcp_config.py, rest-api/services/gcp_db_daemon.py, rest-api/services/gcp_utils.py, rest-api/services/system_utils.py
During startup, stop any previously running instance instead of exiting with warning.
=> Updated google proxy service code to include the test replication database.

rest-api/data_gen/fake_biobank_samples_generator.py, rest-api/offline/biobank_samples_pipeline.py, rest-api/test/unit_test/offline_test/biobank_samples_pipeline_test.py
Tests here are flaky / lacking. I tested this against my local server and verified things seem to be working.
Some TODO's in this PR, questions for @robabram
=> Update fake biobank sample CSV generation to include new columns

rest-api/dao/metrics_cache_dao.py, rest-api/test/unit_test/api_test/participant_counts_over_time_api_test.py
=> [DA-870] fix race calculate algorithm

rest-api/config/config_stable.json
Need to confirm this is the correct service account.
=> [DA-889] Whitelist IPs in STABLE for Coalfire

rest-api/dao/participant_counts_over_time_service.py, rest-api/test/unit_test/api_test/participant_counts_over_time_api_test.py
Add initial tests to highlight the issue.
I'm committing these failing tests only at first for discussion.
=> [DA-873] participant counts over time EHR Consent date filtering issue

rest-api/cron_default.yaml
change cronjob time for ParticipantCountsOverTime
=> [DA-915] change cronjob time

rest-api/etl/run_cloud_etl.sh, rest-api/etl/setup_database_for_etl.sh, rest-api/etl/setup_local_database_for_etl.sh
Added '--local' flag to mysqlimport statements to fix error accessing local files.
=> [DA-668] ETL scripts: add cli flags to set paths, removed hardcoded paths

rest-api/tools/ehr_upload_for_organization.py, rest-api/tools/ehr_upload_for_organization.sh
A ticket was raised 
[DA-842](https://precisionmedicineinitiative.atlassian.net/browse/DA-842) addressing the need to resync VA ehr consent files into aou179, partly because there's a 30 day lifecycle on google bucket files (and they forgot to get them) and partly because we stopped the cron job to sync all consents across the board. We removed this ability (syncing a single awardee) so I'm putting it back in.
=> DA-943 Create script to upload ehr consent for a single awardee

rest-api/alembic/versions/77422a4d8e14_dv_salivary_fields.py
Fixes down revision to fix dual head issue.
=> [DA-956] Update migration down revision

rest-api/api/participant_counts_over_time_api.py, rest-api/api/public_metrics_api.py, rest-api/api_util.py, rest-api/dao/metrics_cache_dao.py, rest-api/dao/participant_counts_over_time_service.py, rest-api/main.py, rest-api/participant_enums.py, rest-api/test/unit_test/api_test/public_metrics_api_test.py
public metrics API
create new endpoints
=> [DA-933] create endpoints for public metrics export api

rest-api/offline/biobank_samples_pipeline.py, rest-api/test/unit_test/offline_test/biobank_samples_pipeline_mysql_test.py
show records that sent_count <= received_count in received report
=> [DA-928] add sent_count=0 and received_count=1 to received report

rdr_common/fhir_utils.py, rest-api/dao/dv_order_dao.py, rest-api/test/unit_test/lib_common_test/fhir_utils_test.py
also extend the reader and reader tests
=> use SimpleFhirR4Reader in DvOrderDao

rest-api/services/gcp_config.py, rest-api/services/gcp_db_daemon.py, rest-api/services/gcp_utils.py
Change Staging replica instance name to 'rdrbackupdb1'.
Code cleanup and organization.
This also adds a new command line parameter "--enable-replica" to enable connections to the replica SQL instances for each project.
=> Add option to connect to replica SQL instances.

rest-api/dao/participant_summary_dao.py
fix enrollment_status_core_stored_sample_time 3000-01-01 bug
=> [DA-999] fix enrollment_status_core_stored_sample_time 3000-01-01 bug

rest-api/config/config_prod.json
whitelist_IPs_to_prod_for_awardee_service_account
=> [PD-2800] whitelist_IPs_to_prod_for_awardee_service_account

rest-api/dao/genomics_dao.py
add some methods to genomics_dao.py, submit this separately so that anyone can use it and avoid possible conflict.
=> [DA-1022] add_method_to_genomics_dao

rest-api/config.py, rest-api/config/config_prod.json, rest-api/config/config_stable.json, rest-api/offline/update_ehr_status.py
This cron job needs to be configurable to run against the `stable` environment's curation buckets.
=> DA-1052 make update_ehr_status cron job configurable for stable

rest-api/cron_default.yaml, rest-api/genomic/genomic_set_file_handler.py, rest-api/offline/genomic_pipeline.py, rest-api/offline/main.py, rest-api/test/test-data/Genomic-Test-Set-test-2.csv, rest-api/test/test_data.py, rest-api/test/unit_test/api_test/genomic_set_file_handler_test.py, rest-api/test/unit_test/offline_test/genomic_pipeline_test.py
cronjob for genomic water line dry run
=> [DA-1035] Wangy70/cronjob for genomic dry run

README.md, ci/test_pre_push.sh, rest-api/alembic/versions/a43f72b7c848_update_code_procs.py, rest-api/api/questionnaire_response_api.py, rest-api/dao/base_dao.py, rest-api/main.py, rest-api/model/database.py, rest-api/test/unit_test/api_test/participant_answers_test.py, rest-api/test/unit_test/unit_test_util.py
FYI, in this PR I have updated the Pylint maximum line limit to 119 characters. If this is an issue, let me know.
I have added the `participant_answers_view` view to allow getting participant answers quickly. Example: 
```
select * from participant_answers_view pav where pav.participant_id = 216950573 and pav.module = 'OverallHealth';
```
=> [DA-1067] Create new API for retrieving participant questionnaire answers 

rest-api/config/config_staging.json, rest-api/config/config_test.json
add config to test and staging env
=> [DA-1035] add config to test and staging env

rest-api/config/config_prod.json
add new service account and ip to prod whitelist
=> [PD-2037] add new service account and ip to prod whitelist

rest-api/cron_sandbox.yaml
remove genomic cron job from sandbox
=> [DA-1035] remove genomic cron job from sandbox

rest-api/cloud_utils/google_sheets.py
Existing code for the `GoogleSheetCSVReader` used the `requests` library which does not work in GAE. This PR updates it to use `httplib2`.
=> DA-1099 EHR Metrics Cron Job: Fix google sheet reader

rest-api/dao/metrics_ehr_service.py
This is a cleanup merge for code already out in `v1-45-rc4`
=> EHR Metrics logic from hotfix `v1-45-rc4` (`v1-45-rc3-hotfix`)

rest-api/offline/biobank_samples_pipeline.py
exclude genomic subfolder for biobank sample pipeline
=> [DA-1035] exclude genomic subfolder for biobank sample pipeline

rest-api/config/config_stable.json
add new service account and ip to stable whitelist
=> [PD-3291] add new service account and ip to stable whitelist

rest-api/genomic/genomic_set_file_handler.py
ignore result file when pickup input file
=> [DA-1115] ignore result file when pickup input file

rest-api/genomic/genomic_biobank_menifest_handler.py, rest-api/genomic/genomic_set_file_handler.py, rest-api/test/unit_test/api_test/genomic_set_file_handler_test.py, rest-api/test/unit_test/offline_test/genomic_pipeline_test.py
export ny_flag with Y or N instead of bool
=> [DA-1023] export ny_flag with Y or N instead of bool

rest-api/etl/etl.sql
Changed back from View to a INSERT INTO SELECT, because filtering took way too long in that statement.  Instead, I added multiple steps after creating the src_clean table to mark which records should be filtered.  This keeps the execution speed of the script about the same as before filtering.
=> [DA-944] refactored primary etl script

.gitignore, rest-api/api/data_gen_api.py, rest-api/app_base.yaml, rest-api/client_cli/README.md, rest-api/client_cli/rdr.py, rest-api/main.py, rest-api/requirements.txt, rest-api/service_libs/__init__.py, rest-api/service_libs/_program_template.py, rest-api/service_libs/verify_environment.py, rest-api/services/_daemon_template.py, rest-api/services/gcp_config.py, rest-api/services/gcp_db_daemon.py, rest-api/services/gcp_utils.py, rest-api/services/system_utils.py, rest-api/test/unit_test/cloud_utils_test/google_sheets_test.py
Added generic program launcher in 'client_cli'.
Added program template for use with the generic launcher.
Added a program to verify the local environment is configured correctly.
Finished creating functions to work with GCP.
=> Foundation PR for new client tool and python based GCP utilities.

rest-api/genomic/genomic_set_file_handler.py
genomic pipeline:put file exist check after timestamp check
=> [DA-1023] genomic pipeline:put file exist check after timestamp check

rest-api/tools/import_questionnaires.sh
These are additional questionnaires to be loaded when setting up a new DB.
=> Added additional questionnaires for new DB setup

rest-api/alembic/versions/80327f136364_update_genomic_set_member_table.py
=> [DA-1131] fix alembic version conflict

pylintrc, rest-api/dao/biobank_order_dao.py, rest-api/dao/participant_summary_dao.py, rest-api/dao/physical_measurements_dao.py, rest-api/test/unit_test/dao_test/biobank_order_dao_test.py, rest-api/test/unit_test/dao_test/participant_summary_dao_test.py
covering more cases. i.e. amending orders, cancelling, etc. Added specific test case examples from the PRD.
=> DA-1097 refactor number of distinct visit counting 

rest-api/alembic/versions/71614b7c6482_filter_ghosts_from_views.py
added filtering of `is_ghost_id is not true`
=> DA-964 refactor ppi participant views for qa table exporter

rest-api/config/config_prod.json, rest-api/config/config_stable.json
add ip white list for security app scan
=> [DA-961] add ip white list for security app scan

rest-api/config/config_prod.json, rest-api/config/config_stable.json
add ip to whitelist for service account
=> [PD-2165] add ip to whitelist for service account

rest-api/api/metrics_ehr_api.py, rest-api/dao/metrics_ehr_service.py, rest-api/main.py, rest-api/test/unit_test/api_test/metrics_ehr_api_test.py, rest-api/test/unit_test/dao_test/ehr_dao_test.py
Update the EHR metrics API to only render current data instead of data-over-time
=> [DA-1119] ehr metrics api update (simplified to current view)

rest-api/model/bq_base.py, rest-api/model/bq_participant_summary.py, rest-api/services/gcp_utils.py, rest-api/tools/__main__.py, rest-api/tools/tool_libs/__init__.py, rest-api/tools/tool_libs/_program_template.py, rest-api/tools/tool_libs/bq_migrate.py, rest-api/tools/tool_libs/tools.bash, rest-api/tools/tool_libs/verify_environment.py
This PR creates a new directory named `tools_libs` under `rest-api/tools/`. This will be the place for cli tools written using the new python GCP tooling. 
I have also added Bash Completion support for the new tools, see `rest-api/tools/tool_libs/tools.bash`.  You can use it by running: `. tools/tool_libs/tools.bash`.
You can run the new tools by using `python -m tools --help`.
=> [DA-1185] Build BQ tools and schema support

rest-api/dao/genomics_dao.py, rest-api/genomic/genomic_biobank_menifest_handler.py
When update the package_id and client_id, check both biobank_id and genome_type to make sure we are updating the right record.
=> [DA-1085] genomic manifest ingestion modification

README.md, rest-api/dao/metrics_cache_dao.py, rest-api/participant_enums.py, rest-api/test/unit_test/api_test/participant_counts_over_time_api_test.py, rest-api/test/unit_test/api_test/public_metrics_api_test.py
Dashboard change for multiple gender
=> [DA-1190] Dashboard change for multiple gender

rest-api/alembic/versions/fdc0fb9ca67a_rename_participant_view.py
A recent update renamed 'participant_view' to 'particpant_view'.  This PR renames it back.
=> [ROC-20] fixed misspelling of view name

rest-api/alembic/versions/629f994cc809_add_gender_identity_to_view.py
Updated `participant_view` to include new `gender_identity` table field.
=> [ROC-21] Added new gender_identity field to view

rest-api/config/config_prod.json
=> add_storefront_role_in_prod

doc/creating_an_rdr_environment.md, rest-api/config/config_test_ptsc_1.json, rest-api/cron_ptsc.yaml, rest-api/tools/auth_setup.sh, rest-api/tools/build_cron_yaml.py, rest-api/tools/deploy_app.sh, rest-api/tools/setup_database.sh
This is the new configuration and tool changes necessary to set up the new `all-of-us-rdr-ptsc-1-test` environment.
Also included is a `doc/creating_an_rdr_environment.md` file that documents the process.
=> [DA-1162] preparing config and tooling for new ptsc test 1 env

rest-api/alembic/versions/0041519860c1_create_answer_table_for_gnder_and_race.py
=> [DA-1176] fix alembic conflict

README.md
=> [DA-1176] update readme

rest-api/api/mayolink_api.py
original error message for this code:
>IOError: [Errno 2] No such file or directory: '/base/data/home/apps/s~all-of-us-rdr-prod/v1-49-rc2.418981292352439975/data/mayo_order.xml'
=> [ROC-47] HOTFIX for salivary mayolink api bug

rdr_client/salivary_order.py
Just a little fix for finding orderId in a client tool.
=> add logic to get orderId for request or delivery

rest-api/api/dv_order_api.py, rest-api/test/test-data/dv_order_api_put_supply_delivery.json
add conditional that looks for existence of expected-delivery-date
=> ROC-43 remove requirement for expected delivery date

rest-api/tools/setup_database.sh
iterating every time we need to create a new environment
=> updated setup-database tool script

rest-api/offline/biobank_samples_pipeline.py, rest-api/test/unit_test/offline_test/biobank_samples_pipeline_mysql_test.py
Modify Withdrawal Report to only send Biobank IDs of participants that had samples collected
=> [DA-1203] modify withdrawal report

rest-api/dao/participant_summary_dao.py, rest-api/model/biobank_stored_sample.py, rest-api/model/participant_summary.py
Also includes a small fix for the bigquery PRs.  I forgot to define an index on the biobank_stored_samples table.
=> [ROC-54] Force eager loading of patient status records

rest-api/dao/bigquery_sync_dao.py, rest-api/test/unit_test/dao_test/bigquery_sync_dao_test.py
This PR creates a DAO object for the `bigquery_sync` table and adds a participant summary json generator, which the output of will be stored in the mysql `bigquery_sync` table for transfer over to BigQuery.
=> [DA-1189] Create BigQuery participant summary json and store in mysql

.circleci/config.yml, rest-api/offline/main.py
Also un-commented Jira ticket creation call.
=> point to the correct cron function for backfill

rest-api/config/config_prod.json
=> [ROC-70] white list ip

rest-api/alembic/versions/8fa4d8f2277c_modify_metrics_lifecycle_cache_table.py
set not null for primary key column
=> [DA-1231] set not null for primary key column

rest-api/services/gcp_utils.py, rest-api/services/system_utils.py, rest-api/tools/tool_libs/__init__.py, rest-api/tools/tool_libs/sync_consent.py
This one does it all, its a good one to look over at what the GCP utility functions can do. It copies files to and from local disk and buckets, copies files between buckets. Invokes a temporary google_sql_proxy process to run queries the database.  Also includes a CLI progress bar to follow the progress of the sync.
**Invocation**
1. `python -m tools sync-consents --project all-of-us-rdr-prod --service-account configurator@all-of-us-rdr-prod.iam.gserviceaccount.com`
2. `python -m tools sync-consents --project all-of-us-rdr-prod --service-account configurator@all-of-us-rdr-prod.iam.gserviceaccount.com --org-id VA_PALO_ALTO_VAMC`
=> New gen tool to sync consent EHR files to HPO buckets.

rest-api/offline/biobank_samples_pipeline.py, rest-api/offline/main.py
move biobank_sample_report big sql to run on backup_db
=> [DA-1247] move_biobank_sample_report_sql_to_backup_db

rest-api/dao/metrics_cache_dao.py, rest-api/test/unit_test/api_test/participant_counts_over_time_api_test.py
=> [DA-1231] dashboard lifecycle hot fix

rest-api/client_cli/README.md, rest-api/data_gen/generators/hpo.py, rest-api/data_gen/generators/questionnaires.py, rest-api/service_libs/spec_data_generator.py, rest-api/services/gcp_utils.py
Allows vertical or horizontal sheets for spec participant data.
Bug fixes
Exclude same Sites that the import_organization.sh script does so we don't try to use a Site not available in the RDR.
=> Updates to the spec data generator tool

rest-api/tools/download_data_files.py
added the real bucket name for the `export_organizations.sh` replacement tool.
=> addding bucket name to download tool

rdr_service/config/config_stable.json
whitelist_IPs_to_stable_for_awardee_service_account
=> [ROC-99,ROC-100] whitelist_IPs_to_stable_for_awardee_service_account

rest-api/dao/questionnaire_dao.py
workaround for codebook changes for master
=> workaround for codebook changes for master

rest-api/dao/questionnaire_dao.py, rest-api/tools/tool_libs/sync_consent.py
modify sync consent script for master
=> [ROC-85] modify sync consent script for master

rest-api/config/config_stable.json, rest-api/dao/questionnaire_dao.py
This is for master branch
whitelist_IPs_to_stable_for_awardee_service_account
=> [ROC-99,ROC-100]  whitelist_IPs_to_stable_for_awardee_service_account

requirements.in, requirements.txt, tests/cloud_util_tests/test_bigquery.py, tests/cloud_util_tests/test_bigquery_schema.py, tests/cloud_util_tests/test_google_sheets.py, tests/helpers/mysql_helper.py, tests/test_environment.py
Added a couple of unit tests.
You can envoke these tests by running `python -m unittest discover -s tests`
=> Create new unit test directory at root of project.

rdr_service/model/bq_base.py, requirements.in, requirements.txt, tests/cloud_util_tests/test_bigquery_schema.py, tests/test_environment.py
Fixed depreciated warning when using `collections.Mapping`.
=> Fix tests so they run correctly.  Changed package to flask_restful.

rest-api/dao/bigquery_sync_dao.py, rest-api/dao/dv_order_dao.py, rest-api/model/bq_participant_summary.py
Removed fields that PTSC removed from codebook.
=> Fixed missing barcode in API call.

rdr_service/alembic/env.py
import database for alembic env
=> fix alembic generate schema issue

.gitignore, rdr_service/config.py, tests/.test_configs/db_config.json, tests/api_tests/test_participant_counts_over_time.py, tests/api_tests/test_public_metrics.py, tests/cron_job_tests/test_genomic_validation.py, tests/helpers/mysql_helper.py, tests/helpers/unittest_base.py
1. setup_configs_for_unittest
2. unittest_for_metrics_api
=> Setup configs for unittest and unittest for metrics api

tests/api_tests/test_awardee_api.py, tests/dao_tests/test_organization_dao.py, tests/helpers/unittest_base.py
=> unittest for org and awardee

rdr_service/dao/base_dao.py, rdr_service/model/measurements.py, tests/api_tests/test_physical_measurements_api.py, tests/dao_tests/test_physical_measurements_dao.py, tests/dao_tests/test_site_dao.py, tests/helpers/unittest_base.py
unittest_for_physical_measurement
=> unittest_for_physical_measurement

tests/api_tests/test_check_ppi_data.py
=> add ppi data check test

.gitignore, rdr_service/api_util.py, rdr_service/genomic/genomic_biobank_menifest_handler.py, rdr_service/genomic/genomic_set_file_handler.py, rdr_service/offline/biobank_samples_pipeline.py, rdr_service/offline/exclude_ghost_participants.py, rdr_service/offline/sql_exporter.py, rdr_service/services/gcp_db_daemon.py, rdr_service/storage.py, rdr_service/test/test_data.py, rdr_service/test/unit_test/offline_test/sync_consent_files.py, tests/cron_job_tests/test_genomic_pipeline.py, tests/helpers/unittest_base.py
1. storage provider to mock local cloud storage
2. genomic pipeline test case
3. the GoogleCloudStorageFile part need to be test in the real cloud env in the future
=> storage_provider_to_mock_local_cloud_storage

rest-api/api/bigquery_task_queue_api.py, rest-api/main.py, rest-api/model/bq_pdr_participant_summary.py
I mixed up the Not sign, this fixes it.
=> fix participant withdrawn view

rdr_service/dao/metrics_cache_dao.py
modify_dashboard_lifecycle_criteria_for_devel
=> [DA-1297] modify_dashboard_lifecycle_criteria_for_devel

tests/helpers/mysql_helper.py
=> Fix temporary database directory location

pylintrc, rdr_service/services/system_utils.py, tests/helpers/mysql_helper.py
Remove legacy directories from pylintrc.
=> Redo reverted changes

rest-api/tools/deploy_app.sh
Commented out the BigQuery migration tool call.
=> Deploy script fix

rest-api/dao/bq_participant_summary_dao.py, rest-api/model/__init__.py, rest-api/model/bq_pdr_participant_summary.py, rest-api/model/bq_questionnaires.py, rest-api/offline/bigquery_sync.py, rest-api/test/unit_test/dao_test/participant_summary_dao_test.py
=> Fix PDR typos

.gitignore, rdr_service/app_nonprod.yaml, rdr_service/config.py, rdr_service/main.py, rdr_service/services/gunicorn_config.py, rdr_service/services/supervisor.conf
Added shutdown code to stop supervisor.
=> Fixes for environment variable usage.

rdr_service/app_base.yaml, rdr_service/app_nonprod.yaml, rdr_service/app_prod.yaml, rdr_service/data_gen/fake_participant_generator.py, rdr_service/storage.py
Some python 2 to python 3 updates in fake data generator.
=> Fix interator issue and consolidate yaml config

rest-api/dao/bq_participant_summary_dao.py, rest-api/offline/bigquery_sync.py
Tweaks to sync process.
Ensure we rebuilt the oldest participant records first.
=> BigQuery process tweaks

rest-api/api/organization_hierarchy_api.py, rest-api/api_util.py, rest-api/dao/bq_participant_summary_dao.py, rest-api/dao/organization_hierarchy_sync_dao.py, rest-api/main.py, rest-api/offline/bigquery_sync.py, rest-api/test/unit_test/api_test/hierarchy_content_api_test.py
Hierarchy content implementation
=> [DA-1298] Hierarchy content implementation

rest-api/cron_careevo.yaml, rest-api/cron_default.yaml, rest-api/cron_ptsc.yaml, rest-api/cron_sandbox.yaml
=> [DA-1031] retire old metrics cron jobs

rest-api/dao/bigquery_sync_dao.py, rest-api/dao/bq_hpo_dao.py, rest-api/dao/bq_organization_dao.py, rest-api/dao/bq_site_dao.py, rest-api/offline/bigquery_sync.py, rest-api/tools/import_organizations.py
This fixes a minor issue with the BigQuery sync process and also fixes the `localhost` issue when running `import_organizations.sh`.
=> BigQuery Fixes for Sync process and Import Organizations

rdr_service/dao/dv_order_dao.py, tests/dao_tests/test_dv_order_dao.py
Changed the condition to evaluate to True if there is an available 'expected-delivery-date' URL.
Also expanded test_dv_order_dao.py to test for the expected delivery date and other expected data.
=> [DA-1316] Bug Fix for Salivary Expected Delivery Date

rest-api/cron_default.yaml
modify skew duplication cron job time to 1:00
=> modify_skew_duplication_cron_job_time

rest-api/dao/organization_hierarchy_sync_dao.py, rest-api/test/unit_test/api_test/hierarchy_content_api_test.py
Document updated, just follow it do the change.
=> modify_hierarchy_content_api

rdr_service/dao/bigquery_sync_dao.py, rdr_service/dao/bq_code_dao.py, rdr_service/dao/bq_hpo_dao.py, rdr_service/dao/bq_organization_dao.py, rdr_service/dao/bq_participant_summary_dao.py, rdr_service/dao/bq_pdr_participant_summary_dao.py, rdr_service/dao/bq_questionnaire_dao.py, rdr_service/dao/bq_site_dao.py, rdr_service/main.py, rdr_service/offline/bigquery_sync.py, rdr_service/offline/main.py, rdr_service/services/flask.py, rdr_service/services/gcp_logging.py
Also includes App Engine 2 logging fixes.
=> [DA-1345] Py3: Move BigQuery read ops to backup db instance.

rest-api/dao/bq_questionaire_dao.py, rest-api/model/__init__.py, rest-api/model/bq_questionnaires.py
Tone down ignored module messages.
=> [PDR-3] Add additional questionnaire modules to PDR BQ.

rdr_service/model/bq_pdr_participant_summary.py
Missed fixing indentation in py3-PDR-3 PR.
=> Reformat code to python 3 standard

.gitignore, rdr_service/api/base_api.py, rdr_service/api/cloud_tasks_api.py, rdr_service/api/data_gen_api.py, rdr_service/api/import_codebook_api.py, rdr_service/api/questionnaire_response_api.py, rdr_service/app_util.py, rdr_service/dao/biobank_order_dao.py, rdr_service/dao/bq_participant_summary_dao.py, rdr_service/main.py, rdr_service/offline/bigquery_sync.py, rdr_service/offline/sync_consent_files.py, rdr_service/queue.yaml, rdr_service/services/gcp_cloud_tasks.py, rdr_service/services/gcp_logging.py, rdr_service/storage.py, requirements.in, requirements.txt
Lots of fixes related to background tasks.
=> [DA-1357] Convert background tasks to use Cloud Task API

rest-api/dao/metrics_cache_dao.py, rest-api/dao/participant_counts_over_time_service.py, rest-api/test/unit_test/api_test/participant_counts_over_time_api_test.py
dashboard_enrollmentstatus_filter_for_total
=> dashboard_enrollmentstatus_filter_for_total

rdr_service/api/base_api.py, rdr_service/app_util.py, rdr_service/dao/base_dao.py, rdr_service/main.py, rdr_service/offline/main.py, rdr_service/services/gcp_logging.py, rdr_service/services/gcp_utils.py, rdr_service/storage.py, rdr_service/tools/tool_libs/oauth_token.py, rdr_service/version_api.py
Some tooling fixes.
Fix google bucket provider Exists function.
Logging needs to be thread safe to run correctly under Gunicorn.
Fix duplicate names preventing genomic pipeline cron job from running.
=> [DA-1368] Fix logging issues with Python 3.

rdr_service/storage.py
Clean bucket name function arguments, this is the fix for DA-1367.
=> [DA-1369] Retry google bucket timeout errors 

rdr_service/api/base_api.py, rdr_service/api/cloud_tasks_api.py, rdr_service/api/data_gen_api.py, rdr_service/api/import_codebook_api.py, rdr_service/api/questionnaire_response_api.py, rdr_service/app_nonprod.yaml, rdr_service/cloud_utils/gcp_cloud_tasks.py, rdr_service/dao/bq_participant_summary_dao.py, rdr_service/dao/organization_hierarchy_sync_dao.py, rdr_service/offline/bigquery_sync.py, rdr_service/offline/sync_consent_files.py, rdr_service/queue.yaml, rdr_service/services/flask.py, rdr_service/services/gunicorn_config.py
=> [DA-1371] Fix organization API 500 error.

rdr_service/cloud_utils/gcp_cloud_tasks.py, rdr_service/config.py, rdr_service/config/config_prod.json, rdr_service/config/config_sandbox.json, rdr_service/config/config_stable.json, rdr_service/config/config_staging.json, rdr_service/config/config_test.json, rdr_service/config/config_test_careevo.json, rdr_service/config/config_test_ptsc_1.json, rdr_service/config/config_test_ptsc_2.json, rdr_service/config/config_test_ptsc_3.json, rdr_service/dao/bq_participant_summary_dao.py, rdr_service/model/bq_questionnaires.py, rdr_service/offline/bigquery_sync.py, rdr_service/queue.yaml, rdr_service/services/gcp_config.py, rdr_service/tools/tool_libs/app_engine_manager.py, rdr_service/tools/tool_libs/tools.bash
Tuning and fixes for BigQuery and background tasks.
=> [DA-1374] Fix app config during deployment

rdr_service/tools/__main__.py, rdr_service/tools/tool_libs/README.md, rdr_service/tools/tool_libs/__init__.py, rdr_service/tools/tool_libs/alembic.py, rdr_service/tools/tool_libs/app_engine_manager.py, rdr_service/tools/tool_libs/bq_migrate.py, rdr_service/tools/tool_libs/tools.bash, setup.py
Re-wrote context manager sql proxy activation code to simplify usage in tools.
Added get app config functions to Context Manager.
Both sql proxy and get configs functions are able to be used against localhost and GCP projects.
=> [DA-1376] Add migrations to new deploy tool.

rdr_service/api/public_metrics_api.py, rdr_service/dao/metrics_cache_dao.py, rdr_service/participant_enums.py, tests/api_tests/test_public_metrics.py
add site count stratification for research hub
=> [DA-1306] research_hub_sites_counts_for_devel

rdr_service/services/gcp_utils.py, rdr_service/services/system_utils.py, rdr_service/tools/tool_libs/app_engine_manager.py
Added colors to tools and logging messages.  I know Michael was secretly feeling bad that these tools were only in black and white.
=> Ensure default app credentials are set before deploying.

rdr_service/model/bq_base.py, rdr_service/model/bq_code.py, rdr_service/model/bq_hpo.py, rdr_service/model/bq_organization.py, rdr_service/model/bq_pdr_participant_summary.py, rdr_service/model/bq_questionnaires.py, rdr_service/model/bq_site.py, rdr_service/tools/tool_libs/bq_migrate.py
Make service-account cli arg optional.
=> [PDR-15] Update BigQuery views to allow different partition fields

tests/helpers/unittest_base.py
This should reduce the setup overhead for each unittest, which should hopefully make them run a little faster overall.
=> Only write unittest configs once per run instead of each test.

rdr_service/dao/organization_hierarchy_sync_dao.py, rdr_service/tools/tool_libs/app_engine_manager.py
Use the geocode key from the config to lookup address coordinates.
=> [ROC-265] Add the geocode key to all cloud configs when updating.
